### ISSUE TITLE
Defining groups of privileges and grant Permissions on them

### ISSUE THREAD

**Issue by ReneB** [BUS-OGD/arrthorizer#17]
After some deliberation, we decided that a YAML file is probably easiest to write, read and get to work. This file would look a little like this:

```
read_channel:
  actions:
    - streams/conversations: 
      - index
      - show
    - streams/channels:
      - show
  roles:
    - channel_subscriber

delete_conversation:
  actions:
    - streams/conversations:
      - destroy
  roles:
    - conversation_starter
```

It should be possible to provide multiple files and have them merged.
